name: capsule_new
description: Capsule project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  introduction_slider: ^2.0.1
  flutter_screenutil: ^5.8.4
  get: ^4.6.5
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^9.0.0
  otp_text_field: ^1.1.3
  country_picker: ^2.0.20
  percent_indicator: ^4.2.3
  intl_phone_field: ^3.2.0
  syncfusion_flutter_charts: ^22.1.37
  dio: ^5.2.1+1
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  shared_preferences: 2.2.0
  intl: ^0.18.0
  cached_network_image: ^3.2.3
  syncfusion_flutter_pdf: ^22.1.39
  syncfusion_flutter_pdfviewer: ^22.1.39
  path_provider: ^2.0.15
  google_fonts: ^4.0.4
  getwidget: ^3.1.1
  pdfx: ^2.4.0
  http: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 800

